### ISSUE TITLE
Add missing south american countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#1]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries for this ticket
Brazil (already there)
Colombia 
Argentina
Peru
Venezuela
Chile
Ecuador
Bolivia
Paraguay
Uruguay
Guyana
Suriname
French Guiana (France)
Falkland Islands (UK)

**Comment by MalkaSaba** [comment]
Can I work on this issue?

**Comment by lsmoura** [comment]
> Can I work on this issue?

it's yours! Take a look at the existing .yaml files and go from there!

**Comment by MalkaSaba** [comment]
Thanks. I have started working on it. However, I have a question, how did you get the numeric value for the country and also what format are the images in?

**Comment by lsmoura** [comment]
> Thanks. I have started working on it. However, I have a question, how did you get the numeric value for the country and also what format are the images in?

The images are unicode characters. Look here: https://emojipedia.org/flags/

The numeric value is the value from the iso standard. Look here: https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by MalkaSaba** [comment]
Ok awesome. Thank you. I will look at those.
