### ISSUE TITLE
Add North Africa Countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#10]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Algeria
Egypt
 Libya
 Morocco
Tunisia
~Ceuta~
~Melilla~

**Comment by hosseinnedaee** [comment]
hi @lsmoura 
Can I work on this?

**Comment by lsmoura** [comment]
> Can I work on this?

it's yours! Take a look at the existing .yaml files and go from there!

**Comment by hosseinnedaee** [comment]
@lsmoura I searched but I didn't find Ceuta and Melilla as countries.
Are they counties?!
[Ceuta](https://en.wikipedia.org/wiki/Ceuta)
[Melilla](https://en.wikipedia.org/wiki/Melilla)

**Comment by lsmoura** [comment]
> @lsmoura I searched but I didn't find Ceuta and Melilla as countries.
> Are they counties?!
> [Ceuta](https://en.wikipedia.org/wiki/Ceuta)
> [Melilla](https://en.wikipedia.org/wiki/Melilla)

Apparently, they are not. Feel free to ignore them.
