### ISSUE TITLE
Add Central Africa Countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#11]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Angola
Cameroon
Central African Republic
Chad
Democratic Republic of the Congo
Equatorial Guinea
Gabon
Republic of the Congo
São Tomé and Príncipe

**Comment by yuvalg99** [comment]
I will take it.
