### ISSUE TITLE
Add East Africa Countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#19]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
 Burundi
 Comoros
 Djibouti
 Eritrea
 Ethiopia
 Kenya
 Madagascar
 Malawi
 Mauritius
 Mayotte
 Mozambique
 Réunion
 Rwanda
 Seychelles
 Somalia
 South Sudan
 Tanzania
 Uganda
 Zambia
 Zimbabwe

**Comment by max-arias** [comment]
I can work on this 👍
