### ISSUE TITLE
Add missing Oceania countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#2]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Australia
Papua New Guinea
New Zealand
Fiji
Solomon Islands
Vanuatu
New Caledonia (France)
French Polynesia (France)
Samoa
Guam (US)
Kiribati
Federated States of Micronesia
Tonga
American Samoa (US)
Northern Mariana Islands (US)
Marshall Islands
Palau
Cook Islands (NZ)
Wallis and Futuna (France)
Tuvalu
Nauru
Norfolk Island (Australia)
Niue (NZ)
Tokelau (NZ)
Pitcairn Islands (UK)

**Comment by AlexandreResende** [comment]
Taking it

**Comment by hoop71** [comment]
I will do this one!
