### ISSUE TITLE
Add Central Asia countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#20]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Kazakhstan
Kyrgyzstan
Tajikistan
Turkmenistan
Uzbekistan

**Comment by gauravagrwal** [comment]
I will do this one.

**Comment by manavmehraa** [comment]
I could do this too if required.
