### ISSUE TITLE
Add Eastern Asia countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#21]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
China
Hong Kong
Macau
Japan
Mongolia
North Korea
South Korea

**Comment by gauravagrwal** [comment]
can I do this one too?

**Comment by jayeshmann** [comment]
This one ?

**Comment by lsmoura** [comment]
It's been 14h since the last comment. Let me know if anyone wants to take this one.
