### ISSUE TITLE
Add South-eastern asia countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#22]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Brunei Darussalam
Cambodia
Indonesia
Laos
Malaysia
Myanmar
Philippines
Singapore
Thailand
Timor-Leste
Vietnam

**Comment by jayeshmann** [comment]
Can i take this?

**Comment by vickywane** [comment]
I'll take this up since 2 hours has elapsed
