### ISSUE TITLE
Add Southern asia countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#23]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Afghanistan
Bangladesh
Bhutan
India
Iran
Maldives
Nepal
Pakistan
Sri Lanka

**Comment by Sampratii** [comment]
I am interested.

**Comment by gauravagrwal** [comment]
Can I do this?

**Comment by lsmoura** [comment]
> I am interested.

it's yours! Take a look at the existing .yaml files and go from there!

**Comment by lsmoura** [comment]
> @gaurav-ag10 Can I do this?

Someone else is already working on this one. Check the project issues. There are still a few left.

**Comment by jayeshmann** [comment]
I am interested. Haven't been completed yet?

**Comment by lsmoura** [comment]
It's been 14h since the last comment. Let me know if anyone wants to take this one.

**Comment by sprakash57** [comment]
i can take this. Please assign it to me.
