### ISSUE TITLE
Add western asia countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#24]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Armenia
Azerbaijan
Bahrain
Cyprus
Georgia
Iraq
Israel
Jordan
Kuwait
Lebanon
Oman
Qatar
Saudi Arabia
State of Palestine
Syria
Turkey
United Arab Emirates
Yemen

**Comment by TimeTerminal** [comment]
I can take this one if you'd like.
