### ISSUE TITLE
Add Europe Countries (I)

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#3]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Albania
Andorra
Armenia
Austria
Azerbaijan
Belarus
Belgium
Bosnia and Herzegovina
Bulgaria
Croatia
Cyprus

**Comment by saurabhrajguru** [comment]
Can I pick this up ?

**Comment by lsmoura** [comment]
> Can I pick this up ?

it's yours! Take a look at the existing `.yaml` files and go from there!
