### ISSUE TITLE
Add Europe Countries (II)

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#4]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Czech Republic
Denmark
Estonia
Faroe Islands (Denmark)
Finland
France
Georgia
Germany
Gibraltar (UK)
Greece
Guernsey

**Comment by afflato** [comment]
I would like to work on this.

**Comment by lsmoura** [comment]
> I would like to work on this.

it's yours! Take a look at the existing .yaml files and go from there!
