### ISSUE TITLE
Add Europe Countries (III)

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#5]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries

Hungary
Iceland
Ireland
Isle of Man
Italy
Jersey
Kazakhstan
Kosovo
Latvia
Liechtenstein
Lithuania

**Comment by yuvalg99** [comment]
I'm on it.
