### ISSUE TITLE
Add Europe Countries (IV)

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#6]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Luxembourg
Malta
Moldova
Monaco
Montenegro
Netherlands
North Macedonia
Norway
Poland
Portugal
Romania

**Comment by Joxtacy** [comment]
I can take this one! 🙋‍♂️
