### ISSUE TITLE
Add Europe Countries (V)

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#7]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Russia
San Marino
Serbia
Slovakia
Slovenia
Spain
Svalbard and Jan Mayen Islands (Norway)
Sweden
Switzerland
Transnistria
Turkey
Ukraine
United Kingdom
Vatican City
Åland (within Finland)

**Comment by yuvalg99** [comment]
I will take it.
