### ISSUE TITLE
Add West Africa Countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#8]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
Benin
Burkina Faso
Cabo Verde (Cape Verde)
Côte d'Ivoire (Ivory Coast)
The Gambia
Ghana
Guinea
Guinea-Bissau
Liberia
Mali
Mauritania
Niger
Nigeria
Saint Helena, Ascension and Tristan da Cunha (United Kingdom Overseas Territory)
Senegal
Sierra Leone
Togo

**Comment by shakirandagire** [comment]
Can I work on this

**Comment by lsmoura** [comment]
> Can I work on this

it's yours! Take a look at the existing .yaml files and go from there!
