### ISSUE TITLE
Add South Africa countries

### ISSUE THREAD

**Issue by lsmoura** [lsmoura/countries#9]
If you're working on this ticket leave a comment, so no two people do the same work. After 2h of the comment, I'll start accepting other volunteers.

The PR to fix this issue should include all the countries with all the data.

# List of countries
 Angola
 Botswana
 Comoros
 Democratic Republic of the Congo
 Eswatini (Swaziland)
 Lesotho
 Madagascar
 Malawi
 Mauritius
 Mozambique
 Namibia
 Seychelles
 South Africa
 Tanzania
 Zambia
 Zimbabwe

**Comment by MalkaSaba** [comment]
Hey, I can do this one as well. Let me know.

**Comment by lsmoura** [comment]
> Hey, I can do this one as well. Let me know.

it's yours! Take a look at the existing .yaml files and go from there!
